### ISSUE TITLE
Invlalid URI - The hostname could not be parsed

### ISSUE THREAD

**Issue by cyb3rgh05t** [fscorrupt/docker-plexstatus2discord#1]
is there a problem with the plex.status page

![image](https://user-images.githubusercontent.com/5200101/178345315-7e7cc1ff-dfe6-47cd-bc56-e730da1d1874.png)

**Comment by fscorrupt** [comment]
Must be a local problem on your site, script/container works for me!
![image](https://user-images.githubusercontent.com/45659314/178347191-491920f1-f72c-4fd8-91ed-45abb3668e4d.png)
